version: '3.9'

services:
  www: 
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html" # sync
    ports:
      - 80:80

  postgres:  #INFO: The name of the container is the host
    image: postgres
    environment:
      POSTGRES_DB: "habrdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
